#!/bin/sh

# Set these paths appropriately

BIN="/Users/max/GitHub/bsjobs/treetagger/bin"
CMD="/Users/max/GitHub/bsjobs/treetagger/cmd"
LIB="/Users/max/GitHub/bsjobs/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
