#!/bin/sh

# Set these paths appropriately

BIN="/Users/max/GitHub/bsjobs/treetagger/bin"
CMD="/Users/max/GitHub/bsjobs/treetagger/cmd"
LIB="/Users/max/GitHub/bsjobs/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek-beta.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

