#!/bin/sh

# Set these paths appropriately

BIN="/Users/max/GitHub/bsjobs/treetagger/bin"
CMD="/Users/max/GitHub/bsjobs/treetagger/cmd"
LIB="/Users/max/GitHub/bsjobs/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
