#!/bin/sh

# Set these paths appropriately

BIN="/Users/max/GitHub/bsjobs/treetagger/bin"
CMD="/Users/max/GitHub/bsjobs/treetagger/cmd"
LIB="/Users/max/GitHub/bsjobs/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/middle-high-german-abbreviations-utf8
PARFILE=${LIB}/middle-high-german-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
